dataset:
  directory: ../pyg_data/trec_6_large_distil
  num_classes: 6
  name: trec_6

preprocessing:
  model: bert-large-uncased
  emb_dim: 1024
  device: cuda:1

xp:
  model: model.gat.GAT
  device: cuda:1
  directory: ../results/trec_6/gat-large-gelu-meanpool-h2304-nh8-bz64
  hparams:
    hidden_channels: 2304
    output_dim: 
    num_heads: 8
    dropout: 0.50
    batch_size: 64
    lr: 1e-5
    nb_epochs: 50
    activation: torch.nn.functional.gelu
    pooling: torch_geometric.nn.global_mean_pool
