dataset:
  directory: ../pyg_data/trec_6_distil
  num_classes: 6
  name: trec_6

preprocessing:
  device: cuda:1
  emb_dim: 768
  model: distilbert-base-uncased

xp:
  device: cuda:1
  directory: ../results/trec_6/gcgat-distil-gelu-meanpool-h2304-bz64
  hparams:
    activation: torch.nn.functional.gelu
    batch_size: 64
    dropout: 0.5
    hidden_channels: 2304
    lr: 1e-5
    nb_epochs: 50
    pooling: torch_geometric.nn.global_mean_pool
  model: model.gcgat.GCGAT
