dataset:
  directory: ../pyg_data/trec_6_large
  name: trec_6
  num_classes: 6
  num_relations: 51
preprocessing:
  device: cuda:0
  emb_dim: 1024
  model: bert-large-uncased
xp:
  device: cuda:0
  directory: ../results/trec_6/rgcn-large-leakyrelu-mean-h256-lr1e2-e200-bz64
  hparams:
    activation: torch.nn.functional.leaky_relu
    batch_size: 64
    dropout: 0.5
    hidden_channels: 256
    lr: 1e-2
    nb_epochs: 200
    pooling: torch_geometric.nn.global_mean_pool
  model: model.rgcn.RGCN
