dataset:
  directory: ../pyg_data/arxiv_distil
  name: arxiv
  num_classes: 3
preprocessing:
  device: cuda:1
  emb_dim: 768
  model: distilbert-base-uncased
xp:
  device: cuda:1
  directory: ../results/arxiv/gcn2-distil-gelu-h1536-lr1e2-e200-bz64
  hparams:
    activation: torch.nn.functional.gelu
    batch_size: 64
    dropout: 0.5
    hidden_channels: 1536
    lr: 0.01
    nb_epochs: 200
    pooling: torch_geometric.nn.global_mean_pool
  model: model.gcn2.GCN2
