dataset:
  directory: ../pyg_data/arxiv_distil
  name: arxiv
  num_classes: 3
  num_relations: 51
preprocessing:
  device: cuda:1
  emb_dim: 768
  model: distilbert-base-uncased
xp:
  device: cuda:1
  directory: ../results/arxiv/rgcn-distil-leakyrelu-max-h256-lr1e2-e200-bz64
  hparams:
    activation: torch.nn.functional.leaky_relu
    batch_size: 64
    dropout: 0.5
    hidden_channels: 256
    lr: 1e-2
    nb_epochs: 200
    pooling: torch_geometric.nn.global_max_pool
  model: model.rgcn.RGCN
